# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9529c50c5af4406e9b84fe3fbacd306a940f956442978336e22c2306cbbee36687372970ad46ea5f0f5ffb98388dbef1f74ea9de0ab83da4a80883f6fe517e2d

test:
  secret_key_base: e767babb097e3801e287da126f03f7b85c42a55e5127fbc6846810f5cd79fbbb4ebeef0ee214eb77244a0691b6e2ee4a089c2fee6270714ccf37fcf404228a5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
